//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtActividad
    {
        public int ActividadId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> TareaId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtTarea dtTarea { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
