//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtApartado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtApartado()
        {
            this.dtApartadoArchivoes = new HashSet<dtApartadoArchivo>();
            this.dtProductoApartadoes = new HashSet<dtProductoApartado>();
        }
    
        public int ApartadoId { get; set; }
        public Nullable<int> ArchivoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.DateTime> FechaInicioApartado { get; set; }
        public Nullable<System.DateTime> FechaFinApartado { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Estatus { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtApartadoArchivo> dtApartadoArchivoes { get; set; }
        public virtual dtArchivo dtArchivo { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProductoApartado> dtProductoApartadoes { get; set; }
    }
}
