//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtApartadoArchivo
    {
        public int ApartadoArchivoId { get; set; }
        public Nullable<int> ApartadoId { get; set; }
        public Nullable<int> ArchivoId { get; set; }
    
        public virtual dtApartado dtApartado { get; set; }
        public virtual dtArchivo dtArchivo { get; set; }
    }
}
