//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtArchivo()
        {
            this.dtApartadoArchivoes = new HashSet<dtApartadoArchivo>();
            this.dtApartados = new HashSet<dtApartado>();
            this.dtTareaPasoArchivoes = new HashSet<dtTareaPasoArchivo>();
        }
    
        public int ArchivoId { get; set; }
        public int EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string NombrePath { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public string OrigenCodigo { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<int> OportunidadId { get; set; }
        public Nullable<int> ProductoServicioId { get; set; }
        public Nullable<int> ObjetivoId { get; set; }
        public Nullable<decimal> Tamanio { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> ProyectoId { get; set; }
        public Nullable<int> MuroDetalleId { get; set; }
        public Nullable<int> ReunionId { get; set; }
        public string TipoAcceso { get; set; }
        public Nullable<bool> FromMail { get; set; }
        public Nullable<int> EmailId { get; set; }
        public Nullable<bool> MailDescargado { get; set; }
        public Nullable<int> TicketId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtApartadoArchivo> dtApartadoArchivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtApartado> dtApartados { get; set; }
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtMuroDetalle dtMuroDetalle { get; set; }
        public virtual dtObjetivo dtObjetivo { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtProductoServicio dtProductoServicio { get; set; }
        public virtual dtProyecto dtProyecto { get; set; }
        public virtual dtReunion dtReunion { get; set; }
        public virtual dtTicketServicio dtTicketServicio { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTareaPasoArchivo> dtTareaPasoArchivoes { get; set; }
    }
}
