//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtAtributoValor
    {
        public int AtributoValorId { get; set; }
        public int AtributoId { get; set; }
        public int ValorId { get; set; }
        public string OrigenCodigo { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> OportunidadId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<int> ProductoServicioId { get; set; }
    
        public virtual dtAtributo dtAtributo { get; set; }
        public virtual dtValor dtValor { get; set; }
    }
}
