//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtBitacoraAlmacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtBitacoraAlmacen()
        {
            this.dtBitacoraAlmacenEvidencias = new HashSet<dtBitacoraAlmacenEvidencia>();
        }
    
        public int BitacoraAlmacenId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Accion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string UsuarioAutorizo { get; set; }
        public Nullable<int> AlmacenActionId { get; set; }
        public Nullable<int> ProductoActionId { get; set; }
        public Nullable<double> CantidadEnAlmacen { get; set; }
        public string UbicacionAlmacen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraAlmacenEvidencia> dtBitacoraAlmacenEvidencias { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
    }
}
