//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCampaniaUbicacionAsignado
    {
        public int CampaniaAsignadoId { get; set; }
        public Nullable<int> CampanaId { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
