//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCampaniaContactoContestado
    {
        public int ContactoContestadoId { get; set; }
        public Nullable<int> CampaniaId { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> ChecklistId { get; set; }
        public string ClaveSync { get; set; }
        public Nullable<int> UsuarioContestadoId { get; set; }
        public Nullable<System.DateTime> FechaContestado { get; set; }
        public Nullable<System.DateTime> FechaSync { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtCheckList1 dtCheckList1 { get; set; }
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
