//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCapacitacion
    {
        public int CapacitacionId { get; set; }
        public string TipoLicencia { get; set; }
        public string TipoTramite { get; set; }
        public int AniosVigencia { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.DateTime> FechaExpedicion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaAntiguedad { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaEstatus { get; set; }
        public string Curp { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public Nullable<short> Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string LugarOrigen { get; set; }
        public Nullable<bool> DonacionOrganos { get; set; }
        public int UsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioBiometrico { get; set; }
        public string Correo { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Lada { get; set; }
        public string RefAd { get; set; }
        public Nullable<bool> ImprimeDir { get; set; }
        public string Ben1Nombre { get; set; }
        public string Ben1APaterno { get; set; }
        public string Ben1AMaterno { get; set; }
        public string Ben1Parentezco { get; set; }
        public Nullable<decimal> Ben1Porcentaje { get; set; }
        public string Ben2Nombre { get; set; }
        public string Ben2APaterno { get; set; }
        public string Ben2AMaterno { get; set; }
        public string Ben2Parentezco { get; set; }
        public Nullable<decimal> Ben2Porcentaje { get; set; }
        public string Ben3Nombre { get; set; }
        public string Ben3APaterno { get; set; }
        public string Ben3AMaterno { get; set; }
        public string Ben3Parentezco { get; set; }
        public Nullable<decimal> Ben3Porcentaje { get; set; }
        public string TipoVig { get; set; }
        public string FolioExpediente { get; set; }
        public string NumeroFolio { get; set; }
        public Nullable<bool> Corazon { get; set; }
        public Nullable<bool> Higado { get; set; }
        public Nullable<bool> Rinon { get; set; }
        public Nullable<bool> Corneas { get; set; }
        public Nullable<int> Semana { get; set; }
        public string Mes { get; set; }
        public string Escolaridad { get; set; }
        public string Sexo { get; set; }
        public string ReciboBancario { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Certificado { get; set; }
        public Nullable<System.DateTime> FechaCertificacion { get; set; }
        public string Poblacion { get; set; }
        public string Municipio { get; set; }
        public string ZonaEconomica { get; set; }
        public string Transporte { get; set; }
        public Nullable<bool> Foraneo { get; set; }
        public Nullable<int> TramiteId { get; set; }
        public Nullable<int> CiudadanoId { get; set; }
        public Nullable<bool> Van { get; set; }
        public Nullable<bool> Bus { get; set; }
        public Nullable<bool> Taxi { get; set; }
        public string FolioPago { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string FolioConocer { get; set; }
        public string Entidad { get; set; }
    
        public virtual dtCiudadano dtCiudadano { get; set; }
        public virtual dtTramite dtTramite { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
    }
}
