//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCasoDocumento
    {
        public int CasoDocumentoId { get; set; }
        public Nullable<int> TipoCreditoId { get; set; }
        public Nullable<int> TipoProductoId { get; set; }
        public Nullable<int> CampoId { get; set; }
        public Nullable<int> DocumentoId { get; set; }
        public int EmpresaId { get; set; }
        public int UsuarioCreadorId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
