//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCampania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCampania()
        {
            this.dtCampaniaContactoes = new HashSet<dtCampaniaContacto>();
            this.dtCampaniaContactoAsignadoes = new HashSet<dtCampaniaContactoAsignado>();
            this.dtCampaniaContactoContestadoes = new HashSet<dtCampaniaContactoContestado>();
            this.dtCampaniaDestinoes = new HashSet<dtCampaniaDestino>();
            this.dtCampaniaProductoes = new HashSet<dtCampaniaProducto>();
            this.dtCampaniaUbicacionAsignadoes = new HashSet<dtCampaniaUbicacionAsignado>();
            this.dtCampaniaUbicacionContestadoes = new HashSet<dtCampaniaUbicacionContestado>();
            this.dtCampaniaUbicacionCuestionarios = new HashSet<dtCampaniaUbicacionCuestionario>();
            this.dtContestadoFormularios = new HashSet<dtContestadoFormulario>();
            this.dtMarkers = new HashSet<dtMarker>();
            this.dtTareas = new HashSet<dtTarea>();
            this.dtTickets = new HashSet<dtTicket>();
        }
    
        public int CampanaId { get; set; }
        public int EmpresaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoCampaniaId { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaPromesa { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string EstatusCode { get; set; }
        public Nullable<int> UsuarioCreadorId { get; set; }
        public Nullable<int> UsuarioModificoId { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtCampaniaTipo dtCampaniaTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContacto> dtCampaniaContactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoAsignado> dtCampaniaContactoAsignadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoContestado> dtCampaniaContactoContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaDestino> dtCampaniaDestinoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaProducto> dtCampaniaProductoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionAsignado> dtCampaniaUbicacionAsignadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionContestado> dtCampaniaUbicacionContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionCuestionario> dtCampaniaUbicacionCuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormulario> dtContestadoFormularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMarker> dtMarkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTicket> dtTickets { get; set; }
    }
}
