//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCampos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCampos()
        {
            this.dtCampoRespuestas = new HashSet<dtCampoRespuesta>();
            this.dtModuloRespuestas = new HashSet<dtModuloRespuesta>();
            this.dtModuloRespuestaOpcions = new HashSet<dtModuloRespuestaOpcion>();
        }
    
        public int CampoId { get; set; }
        public int EmpresaId { get; set; }
        public string ModuloClave { get; set; }
        public string Titulo { get; set; }
        public string Ayuda { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Requerido { get; set; }
        public string CampoClave { get; set; }
        public Nullable<int> VinculoId { get; set; }
        public Nullable<int> CampoGrupoId { get; set; }
        public Nullable<int> CheckListId { get; set; }
        public Nullable<bool> AplicaAgrupacion { get; set; }
    
        public virtual dtCampoGrupo dtCampoGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampoRespuesta> dtCampoRespuestas { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtModulo dtModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloRespuesta> dtModuloRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloRespuestaOpcion> dtModuloRespuestaOpcions { get; set; }
    }
}
