//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCampaniaContacto
    {
        public int CampaniaContactoId { get; set; }
        public int CampaniaId { get; set; }
        public int ContactoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaVisita { get; set; }
        public Nullable<int> CantidadMaxima { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtContacto dtContacto { get; set; }
    }
}
