//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCheckListPreguntas1
    {
        public int PreguntaId { get; set; }
        public int SeccionId { get; set; }
        public int CheckListId { get; set; }
        public string TituloPregunta { get; set; }
        public bool Activa { get; set; }
        public string JsonData { get; set; }
        public int Orden { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public string Tipo { get; set; }
        public string TipoDatoValidacion { get; set; }
        public string ImagenPregunta { get; set; }
        public string PreguntaClave { get; set; }
        public Nullable<bool> AplicaPuntaje { get; set; }
        public string ValidacionTipo { get; set; }
        public string GrupoNombre { get; set; }
        public Nullable<decimal> MaximoValor { get; set; }
    
        public virtual dtCeckListSeccion1 dtCeckListSeccion1 { get; set; }
        public virtual dtCheckList1 dtCheckList1 { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
