//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCheckList1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCheckList1()
        {
            this.dtCampaniaContactoContestadoes = new HashSet<dtCampaniaContactoContestado>();
            this.dtCampaniaUbicacionContestadoes = new HashSet<dtCampaniaUbicacionContestado>();
            this.dtCampaniaUbicacionCuestionarios = new HashSet<dtCampaniaUbicacionCuestionario>();
            this.dtCeckListSeccion1 = new HashSet<dtCeckListSeccion1>();
            this.dtCheckListPreguntas1 = new HashSet<dtCheckListPreguntas1>();
            this.dtContestadoFormularios = new HashSet<dtContestadoFormulario>();
            this.dtContestadoFormularioRespuestas = new HashSet<dtContestadoFormularioRespuesta>();
            this.dtEvaluacions = new HashSet<dtEvaluacion>();
        }
    
        public int CheckListId { get; set; }
        public int EmpresaId { get; set; }
        public string Titulo { get; set; }
        public string Objetivo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> TagId { get; set; }
        public string Clave { get; set; }
        public string Archivo { get; set; }
        public string ArchivoConfigExcel { get; set; }
        public string ArchivoConfigGrid { get; set; }
        public string TplPdf { get; set; }
        public string JsConfiguracion { get; set; }
        public Nullable<int> NumeroPreguntas { get; set; }
        public Nullable<int> TiempoLimite { get; set; }
        public Nullable<bool> Activa { get; set; }
        public Nullable<decimal> CalificacionMinima { get; set; }
        public Nullable<int> TipoLicenciaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoContestado> dtCampaniaContactoContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionContestado> dtCampaniaUbicacionContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionCuestionario> dtCampaniaUbicacionCuestionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCeckListSeccion1> dtCeckListSeccion1 { get; set; }
        public virtual dtTag dtTag { get; set; }
        public virtual dtTipoLicencia dtTipoLicencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCheckListPreguntas1> dtCheckListPreguntas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormulario> dtContestadoFormularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormularioRespuesta> dtContestadoFormularioRespuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtEvaluacion> dtEvaluacions { get; set; }
    }
}
