//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCiudadano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCiudadano()
        {
            this.dtCapacitacions = new HashSet<dtCapacitacion>();
            this.dtLogBloqueoCiudadanos = new HashSet<dtLogBloqueoCiudadano>();
        }
    
        public int CiudadanoId { get; set; }
        public string Curp { get; set; }
        public string Nombre { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public string Calle { get; set; }
        public string NumInt { get; set; }
        public Nullable<int> Colonia { get; set; }
        public string CP { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Localidad { get; set; }
        public Nullable<int> TipoLicencia { get; set; }
        public Nullable<int> AniosVigencia { get; set; }
        public string NumExt { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Correo { get; set; }
        public Nullable<int> ConsecutivoExamenAprobado { get; set; }
        public string FolioExpediente { get; set; }
        public byte[] FotoLic { get; set; }
        public byte[] FingerLeft_10 { get; set; }
        public byte[] FingerLeft_9 { get; set; }
        public byte[] FingerLeft_8 { get; set; }
        public byte[] FingerLeft_7 { get; set; }
        public byte[] thumbs_6 { get; set; }
        public byte[] FingerRight_5 { get; set; }
        public byte[] FingerRight_4 { get; set; }
        public byte[] FingerRight_3 { get; set; }
        public byte[] FingerRight_2 { get; set; }
        public byte[] thumbs_1 { get; set; }
        public string FirmaCapacitacion { get; set; }
        public Nullable<int> UsuarioBiometricos { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Motivo_Bloqueo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCapacitacion> dtCapacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLogBloqueoCiudadano> dtLogBloqueoCiudadanos { get; set; }
    }
}
