//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCotizacionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCotizacionDetalle()
        {
            this.dtCotizacionDetalleSvas = new HashSet<dtCotizacionDetalleSva>();
        }
    
        public int CotizacionDetalleId { get; set; }
        public int CotizacionId { get; set; }
        public string CodigoPlan { get; set; }
        public Nullable<int> PlanProductoId { get; set; }
        public int Cantidad { get; set; }
        public Nullable<bool> TieneEquipo { get; set; }
        public Nullable<decimal> RentaServicio { get; set; }
        public Nullable<decimal> RentaServicioDescuento { get; set; }
        public Nullable<decimal> PagoMensualEquipo { get; set; }
        public string TipoPlan { get; set; }
        public Nullable<decimal> TotalCargoInicial { get; set; }
        public Nullable<int> PlazoNumero { get; set; }
        public string ComentariosAdicionales { get; set; }
        public string CodigoScl { get; set; }
        public string CodigoSAP { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tecnologia { get; set; }
        public Nullable<decimal> DescuentoDesdePlan { get; set; }
        public Nullable<decimal> ModuloDesdePlan { get; set; }
        public Nullable<decimal> PagoMensual { get; set; }
        public Nullable<decimal> PagoMensualExt { get; set; }
        public Nullable<decimal> PrecioActualPlan { get; set; }
        public Nullable<decimal> PrecioPlanPorcentaje { get; set; }
        public Nullable<decimal> PrecioPlanDescuento { get; set; }
        public Nullable<decimal> PrecioPlanExt { get; set; }
        public Nullable<int> CantidadRentas { get; set; }
        public Nullable<decimal> MontoNotificacion { get; set; }
        public Nullable<decimal> CargoInicialDctoPorcentaje { get; set; }
        public Nullable<decimal> CargoInicial { get; set; }
        public Nullable<decimal> CargoInicialDescuento { get; set; }
        public Nullable<decimal> CargoInicialExt { get; set; }
        public Nullable<decimal> TotalPrecioMensualSVA { get; set; }
        public Nullable<decimal> TotalPrecioMensualSVAExt { get; set; }
        public Nullable<decimal> TotalPagoMensual { get; set; }
        public Nullable<decimal> TotalPagoMensualExt { get; set; }
        public string Caracteristicas { get; set; }
        public string DescripcionPlan { get; set; }
        public string Segmento { get; set; }
        public Nullable<bool> AplicaDescuento { get; set; }
        public Nullable<decimal> PrecioPlanUnitarioFinal { get; set; }
        public Nullable<decimal> CargoInicialUnitarioFinal { get; set; }
        public string PartidasJSON { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> PrecioReferencia { get; set; }
        public Nullable<decimal> DescuentoScoring { get; set; }
    
        public virtual dtCotizacion dtCotizacion { get; set; }
        public virtual dtPlanProducto dtPlanProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCotizacionDetalleSva> dtCotizacionDetalleSvas { get; set; }
    }
}
