//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtConcesione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtConcesione()
        {
            this.dtFormaEjecutivas = new HashSet<dtFormaEjecutiva>();
            this.dtTarjetasCirculacionConcesiones = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetonesConcesiones = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesMercantiles = new HashSet<dtTarjetonesMercantile>();
            this.dtTitulosConcesiones = new HashSet<dtTitulosConcesione>();
        }
    
        public int ConcesionId { get; set; }
        public string NoConcesion { get; set; }
        public string NoOperacion { get; set; }
        public string Poligono { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RFC { get; set; }
        public string Calle { get; set; }
        public string NoExt { get; set; }
        public string NoInt { get; set; }
        public string CP { get; set; }
        public string Telefono { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Localidad { get; set; }
        public Nullable<System.DateTime> FechaOtorgamiento { get; set; }
        public string NoEconomico { get; set; }
        public string ClaveRuta { get; set; }
        public string SubClaveRuta { get; set; }
        public string RutaComun { get; set; }
        public string ClaseServMerc { get; set; }
        public string ClaveServicio { get; set; }
        public string Cuenca { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
        public string VigenciaLetra { get; set; }
        public string Region { get; set; }
        public string EstatusPago { get; set; }
        public Nullable<bool> Permanente { get; set; }
        public Nullable<bool> CarreterasCuota { get; set; }
        public Nullable<bool> TaxiLocal { get; set; }
        public Nullable<bool> Nuevo { get; set; }
        public string Preferente { get; set; }
        public string PrimerSustituto { get; set; }
        public string SegundoSustituto { get; set; }
        public string Sitio { get; set; }
        public string NombreSitio { get; set; }
        public string UbicacionSitio { get; set; }
        public string DescTramite { get; set; }
        public string ClaveTramite { get; set; }
        public string RFV { get; set; }
        public string Linea { get; set; }
        public string ClaveVehicular { get; set; }
        public string ClaveClaseTipo { get; set; }
        public string NombreClaseTipo { get; set; }
        public Nullable<int> Cilindros { get; set; }
        public Nullable<int> Llantas { get; set; }
        public string NoSerie { get; set; }
        public string ClaveProcedencia { get; set; }
        public string NombreProcedencia { get; set; }
        public string ClaveTipoPlacas { get; set; }
        public string NombreTipoPlacas { get; set; }
        public string NumeroEconomico { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Placas { get; set; }
        public string NumMotor { get; set; }
        public string CalcomaniaNumero { get; set; }
        public string Uso { get; set; }
        public string ClaveCombustible { get; set; }
        public string Leyenda { get; set; }
        public Nullable<int> CapacidadPasajeron { get; set; }
        public string TituloTarjeton { get; set; }
        public string TarjetaCirculacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> CiudadanoId { get; set; }
        public string OrigenDestino { get; set; }
        public string MunucipioConcesion { get; set; }
        public string MunicipioConcesion { get; set; }
        public byte[] FotoLic { get; set; }
        public byte[] FingerLeft_10 { get; set; }
        public byte[] FingerLeft_9 { get; set; }
        public byte[] FingerLeft_8 { get; set; }
        public byte[] FingerLeft_7 { get; set; }
        public byte[] thumbs_6 { get; set; }
        public byte[] FingerRight_5 { get; set; }
        public byte[] FingerRight_4 { get; set; }
        public byte[] FingerRight_3 { get; set; }
        public byte[] FingerRight_2 { get; set; }
        public byte[] thumbs_1 { get; set; }
        public string FirmaLic { get; set; }
        public string Observaciones { get; set; }
        public string LineaVehiculo { get; set; }
        public string CI { get; set; }
        public string RazonSocial { get; set; }
        public string LocalidadConcesion { get; set; }
        public string ConsecutivoFolioUnico { get; set; }
        public string FolioUnico { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Estatus { get; set; }
        public Nullable<bool> TituloConcesion { get; set; }
        public Nullable<bool> TituloTaxi { get; set; }
        public Nullable<bool> TituloPermiso { get; set; }
        public string TipoTramite { get; set; }
        public string TipoServicio { get; set; }
        public string MunicipioConcesionClave { get; set; }
        public string FolioTituloConcesion { get; set; }
        public Nullable<int> FolioTarjeton { get; set; }
        public Nullable<int> FolioTarjetaCirculacion { get; set; }
        public Nullable<bool> ConcesionCerrada { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> DocumentosImpresos { get; set; }
        public string PeticionCerrar { get; set; }
        public string RespuestaCerrar { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<bool> Mercantil { get; set; }
        public string UsoVehiculo { get; set; }
        public string NumeroAutorizacion { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public Nullable<short> EstadoId { get; set; }
        public Nullable<short> MunicipioId { get; set; }
        public Nullable<short> ColoniaId { get; set; }
        public Nullable<int> ConsecutivoPlacas { get; set; }
        public Nullable<bool> SinAsignar { get; set; }
        public string FolioFormaEjecutiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones { get; set; }
    }
}
