//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtContestadoFormularioRespuesta
    {
        public int ContetadoDetalleId { get; set; }
        public int ContestadoId { get; set; }
        public Nullable<int> CheckListId { get; set; }
        public string PreguntaClave { get; set; }
        public string Valor { get; set; }
        public string ValorBruto { get; set; }
        public string Texto { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string RespuestasClave { get; set; }
        public string Tipo { get; set; }
        public string TipoOrigen { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string PreguntaClaveGeneral { get; set; }
        public Nullable<bool> AplicaPuntaje { get; set; }
        public string TipoDatoValidacion { get; set; }
    
        public virtual dtCheckList1 dtCheckList1 { get; set; }
        public virtual dtContestadoFormulario dtContestadoFormulario { get; set; }
    }
}
