//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCondicionesCredito
    {
        public int CondicionesCreditoId { get; set; }
        public Nullable<bool> TieneEquipo { get; set; }
        public string TipoPlan { get; set; }
        public Nullable<int> CantidadRentas { get; set; }
        public Nullable<decimal> MontoNotificacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Tipo { get; set; }
    }
}
