//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCoordenada
    {
        public long GeopointId { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public byte[] ts { get; set; }
        public System.Data.Entity.Spatial.DbGeography GeographyPoint { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string EmpresaCode { get; set; }
        public System.DateTime FechaServer { get; set; }
        public Nullable<System.DateTime> FechaMobile { get; set; }
        public Nullable<bool> TieneGeocerca { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
