//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtContestadoFormulario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtContestadoFormulario()
        {
            this.dtContestadoFormularioRespuestas = new HashSet<dtContestadoFormularioRespuesta>();
        }
    
        public int ContestadoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> CheckListId { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<System.DateTime> FechaContestado { get; set; }
        public Nullable<System.DateTime> FechaInicioContestado { get; set; }
        public Nullable<int> UsuarioContestadoId { get; set; }
        public System.DateTime FechaSync { get; set; }
        public string ClaveGenerica { get; set; }
        public string JsonHelper { get; set; }
        public string RawJson { get; set; }
        public Nullable<int> CampaniaId { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public string EstatusClave { get; set; }
        public string EstatusApp { get; set; }
        public string Aux1 { get; set; }
        public string PathFicha { get; set; }
        public Nullable<bool> NotificacionEnviada { get; set; }
        public Nullable<System.DateTime> NotificacionEnviadaFecha { get; set; }
        public Nullable<bool> TieneNotificacion { get; set; }
        public Nullable<decimal> Ponderacion { get; set; }
        public Nullable<decimal> PonderacionMaxima { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> TramiteId { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public Nullable<int> NumeroPreguntas { get; set; }
        public Nullable<int> CantidadCorrectas { get; set; }
        public Nullable<decimal> CalificacionMinima { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtCheckList1 dtCheckList1 { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormularioRespuesta> dtContestadoFormularioRespuestas { get; set; }
        public virtual dtTramite dtTramite { get; set; }
    }
}
