//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCrmAsignacion
    {
        public int RegistroId { get; set; }
        public int EmpresaId { get; set; }
        public int UsuarioAsignoId { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<int> OportunidadId { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtGrupo dtGrupo { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
