//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCuotasPDV
    {
        public int CuotaId { get; set; }
        public int DestinoId { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<decimal> CuotaPrepago { get; set; }
        public Nullable<decimal> CuotaPosPago { get; set; }
        public Nullable<decimal> CuotaPortabilidad { get; set; }
        public Nullable<decimal> CuotaMovistarSim { get; set; }
        public int UsuarioCreadorId { get; set; }
        public System.DateTime FechaCreador { get; set; }
        public Nullable<int> UsuarioModificadorId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
