//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtCuenta()
        {
            this.dtArchivoes = new HashSet<dtArchivo>();
            this.dtCampaniaContactoContestadoes = new HashSet<dtCampaniaContactoContestado>();
            this.dtCampaniaUbicacionContestadoes = new HashSet<dtCampaniaUbicacionContestado>();
            this.dtContactoes = new HashSet<dtContacto>();
            this.dtCrmAsignacions = new HashSet<dtCrmAsignacion>();
            this.dtFacturas = new HashSet<dtFactura>();
            this.dtNotas = new HashSet<dtNota>();
            this.dtOportunidads = new HashSet<dtOportunidad>();
            this.dtProductoCompetidors = new HashSet<dtProductoCompetidor>();
            this.dtProyectoes = new HashSet<dtProyecto>();
            this.dtTareas = new HashSet<dtTarea>();
        }
    
        public int CuentaId { get; set; }
        public Nullable<int> ParentCuentaId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string RazonSocial { get; set; }
        public string RFC { get; set; }
        public string Logotipo { get; set; }
        public Nullable<decimal> RevenueAnual { get; set; }
        public Nullable<int> Empleados { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int UsuarioModificoId { get; set; }
        public string URL { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Municipio { get; set; }
        public string Calle { get; set; }
        public string CP { get; set; }
        public string Colonia { get; set; }
        public string TipoAcceso { get; set; }
        public Nullable<bool> Competidor { get; set; }
        public string Fax { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Email { get; set; }
        public string Segmento { get; set; }
        public string NumeroExterior { get; set; }
        public string NumeroInterior { get; set; }
        public string NombreContacto { get; set; }
    
        public virtual dtAccountType dtAccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivo> dtArchivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoContestado> dtCampaniaContactoContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionContestado> dtCampaniaUbicacionContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContacto> dtContactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCrmAsignacion> dtCrmAsignacions { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFactura> dtFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNota> dtNotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProductoCompetidor> dtProductoCompetidors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProyecto> dtProyectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
    }
}
