//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtDestino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtDestino()
        {
            this.dtAprobacionDatosPDVs = new HashSet<dtAprobacionDatosPDV>();
            this.dtAsignacionUsuarioDestinoes = new HashSet<dtAsignacionUsuarioDestino>();
            this.dtBitacoraDocumentosConcesiones = new HashSet<dtBitacoraDocumentosConcesione>();
            this.dtBitacoraLicencias = new HashSet<dtBitacoraLicencia>();
            this.dtCampaniaDestinoes = new HashSet<dtCampaniaDestino>();
            this.dtCampaniaUbicacionAsignadoes = new HashSet<dtCampaniaUbicacionAsignado>();
            this.dtCampaniaUbicacionContestadoes = new HashSet<dtCampaniaUbicacionContestado>();
            this.dtCampaniaUbicacionCuestionarios = new HashSet<dtCampaniaUbicacionCuestionario>();
            this.dtContestadoFormularios = new HashSet<dtContestadoFormulario>();
            this.dtCuotasPDVs = new HashSet<dtCuotasPDV>();
            this.dtFormaEjecutivas = new HashSet<dtFormaEjecutiva>();
            this.dtLicencias = new HashSet<dtLicencia>();
            this.dtMarkers = new HashSet<dtMarker>();
            this.dtMetas = new HashSet<dtMeta>();
            this.dtOportunidads = new HashSet<dtOportunidad>();
            this.dtRegistroEquipoes = new HashSet<dtRegistroEquipo>();
            this.dtTareas = new HashSet<dtTarea>();
            this.dtTarjetasCirculacionConcesiones = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetonesConcesiones = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesMercantiles = new HashSet<dtTarjetonesMercantile>();
            this.dtTickets = new HashSet<dtTicket>();
            this.dtTitulosConcesiones = new HashSet<dtTitulosConcesione>();
            this.dtTokenLogins = new HashSet<dtTokenLogin>();
        }
    
        public int DestinoId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string CodigoDestino { get; set; }
        public string Titulo { get; set; }
        public string CodigoPostal { get; set; }
        public string Direccion { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificoId { get; set; }
        public Nullable<int> AlmacenId { get; set; }
        public string TipoClave { get; set; }
        public Nullable<int> ZonaId { get; set; }
        public Nullable<int> Determinante { get; set; }
        public Nullable<int> DiPropietario { get; set; }
        public string NombrePropietario { get; set; }
        public Nullable<int> DiAtiende { get; set; }
        public string NombreAtiende { get; set; }
        public string Estatus { get; set; }
        public string NumeroInt { get; set; }
        public string NumeroExt { get; set; }
        public string ClasifDelPdv { get; set; }
        public string NivelSocioec { get; set; }
        public string NivelDelPdv { get; set; }
        public Nullable<int> GestionCanalId { get; set; }
        public Nullable<int> CanalId { get; set; }
        public Nullable<int> SubCanalId { get; set; }
        public Nullable<int> CadenaId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> TerritorioId { get; set; }
        public Nullable<int> PosicionesRequeridas { get; set; }
        public Nullable<bool> Validar { get; set; }
        public Nullable<int> SubdirectorId { get; set; }
        public Nullable<int> LiderZonalId { get; set; }
        public string Colonia { get; set; }
        public string DelegacionMunicipio { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string EntreCalles { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public Nullable<int> ColoniaId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> EncargadoId { get; set; }
    
        public virtual dtAlmacen dtAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAsignacionUsuarioDestino> dtAsignacionUsuarioDestinoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraDocumentosConcesione> dtBitacoraDocumentosConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraLicencia> dtBitacoraLicencias { get; set; }
        public virtual dtCadena dtCadena { get; set; }
        public virtual dtCampaniaContactoContestado dtCampaniaContactoContestado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaDestino> dtCampaniaDestinoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionAsignado> dtCampaniaUbicacionAsignadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionContestado> dtCampaniaUbicacionContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionCuestionario> dtCampaniaUbicacionCuestionarios { get; set; }
        public virtual dtCanal dtCanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormulario> dtContestadoFormularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCuotasPDV> dtCuotasPDVs { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtGestionCanal dtGestionCanal { get; set; }
        public virtual dtRegion dtRegion { get; set; }
        public virtual dtSubCanal dtSubCanal { get; set; }
        public virtual dtTerritorio dtTerritorio { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
        public virtual dtUsuario dtUsuario3 { get; set; }
        public virtual dtZona dtZona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMarker> dtMarkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMeta> dtMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtRegistroEquipo> dtRegistroEquipoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTicket> dtTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTokenLogin> dtTokenLogins { get; set; }
    }
}
