//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtDispositivoHistorial
    {
        public int DispositivoHistorialId { get; set; }
        public int EmpresaId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public System.DateTime FechaSync { get; set; }
        public Nullable<int> NivelGSM { get; set; }
        public Nullable<int> NivelBateria { get; set; }
        public string DispositivoClave { get; set; }
        public Nullable<bool> BateriaConectada { get; set; }
        public string TipoConexion { get; set; }
        public Nullable<int> NivelInternet { get; set; }
        public string ValoresJson { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
