//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtDocumento
    {
        public int Id_Documento { get; set; }
        public int TramiteId { get; set; }
        public byte[] Acta_Nacimiento_img { get; set; }
        public string acta { get; set; }
        public byte[] Identificacion_img { get; set; }
        public string identificacion { get; set; }
        public byte[] curp_img { get; set; }
        public string curp { get; set; }
        public byte[] comprobante_img { get; set; }
        public string comprobante { get; set; }
        public byte[] licencia_img { get; set; }
        public string licencia { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<System.DateTime> Fecha_digitalizacion { get; set; }
        public string sCurp { get; set; }
        public byte[] resp_actarob { get; set; }
        public string validacion { get; set; }
        public byte[] tutor_padre { get; set; }
        public string tutor_text { get; set; }
    }
}
