//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtDomicilioEnvio
    {
        public int DomiciliolEnvId { get; set; }
        public int AseguradoId { get; set; }
        public Nullable<int> PaisId1 { get; set; }
        public Nullable<int> EstadoId1 { get; set; }
        public Nullable<int> MunicipioId1 { get; set; }
        public Nullable<int> ColoniaId1 { get; set; }
        public string CP1 { get; set; }
        public string Calle1 { get; set; }
        public string NumInt1 { get; set; }
        public string NumExt1 { get; set; }
        public string EsDomEnvio1 { get; set; }
        public Nullable<int> PaisId2 { get; set; }
        public Nullable<int> EstadoId2 { get; set; }
        public Nullable<int> MunicipioId2 { get; set; }
        public Nullable<int> ColoniaId2 { get; set; }
        public string CP2 { get; set; }
        public string Calle2 { get; set; }
        public string NumInt2 { get; set; }
        public string NumExt2 { get; set; }
        public string EsDomEnvio2 { get; set; }
        public Nullable<int> PaisId3 { get; set; }
        public Nullable<int> EstadoId3 { get; set; }
        public Nullable<int> MunicipioId3 { get; set; }
        public Nullable<int> ColoniaId3 { get; set; }
        public string CP3 { get; set; }
        public string Calle3 { get; set; }
        public string NumInt3 { get; set; }
        public string NumExt3 { get; set; }
        public string EsDomEnvio3 { get; set; }
    }
}
