//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtEstado()
        {
            this.dtMunicipios = new HashSet<dtMunicipio>();
            this.dtMunicipios1 = new HashSet<dtMunicipio>();
            this.dtUsuarios = new HashSet<dtUsuario>();
            this.dtUsuarios1 = new HashSet<dtUsuario>();
            this.dtUsuarios2 = new HashSet<dtUsuario>();
            this.dtUsuarios3 = new HashSet<dtUsuario>();
            this.dtUsuarios4 = new HashSet<dtUsuario>();
            this.dtUsuarios5 = new HashSet<dtUsuario>();
            this.dtUsuarios6 = new HashSet<dtUsuario>();
            this.dtUsuarios7 = new HashSet<dtUsuario>();
            this.dtUsuarios8 = new HashSet<dtUsuario>();
            this.dtUsuarios9 = new HashSet<dtUsuario>();
            this.dtUsuarios10 = new HashSet<dtUsuario>();
            this.dtUsuarios11 = new HashSet<dtUsuario>();
        }
    
        public short EstadoId { get; set; }
        public short PaisId { get; set; }
        public string EstadoNombre { get; set; }
    
        public virtual dtPai dtPai { get; set; }
        public virtual dtPai dtPai1 { get; set; }
        public virtual dtPai dtPai2 { get; set; }
        public virtual dtPai dtPai3 { get; set; }
        public virtual dtPai dtPai4 { get; set; }
        public virtual dtPai dtPai5 { get; set; }
        public virtual dtPai dtPai6 { get; set; }
        public virtual dtPai dtPai7 { get; set; }
        public virtual dtPai dtPai8 { get; set; }
        public virtual dtPai dtPai9 { get; set; }
        public virtual dtPai dtPai10 { get; set; }
        public virtual dtPai dtPai11 { get; set; }
        public virtual dtPai dtPai12 { get; set; }
        public virtual dtPai dtPai13 { get; set; }
        public virtual dtPai dtPai14 { get; set; }
        public virtual dtPai dtPai15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMunicipio> dtMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMunicipio> dtMunicipios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuario> dtUsuarios11 { get; set; }
    }
}
