//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtEstatusLicencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtEstatusLicencia()
        {
            this.dtBitacoraDocumentosConcesiones = new HashSet<dtBitacoraDocumentosConcesione>();
            this.dtBitacoraLicencias = new HashSet<dtBitacoraLicencia>();
            this.dtFormaEjecutivas = new HashSet<dtFormaEjecutiva>();
            this.dtLicencias = new HashSet<dtLicencia>();
            this.dtTarjetasCirculacionConcesiones = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetonesConcesiones = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesMercantiles = new HashSet<dtTarjetonesMercantile>();
            this.dtTitulosConcesiones = new HashSet<dtTitulosConcesione>();
        }
    
        public int EstatusLicenciaId { get; set; }
        public string Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraDocumentosConcesione> dtBitacoraDocumentosConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraLicencia> dtBitacoraLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones { get; set; }
    }
}
