//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtEvaluacion
    {
        public int EvaluacionId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.DateTime> EvaluacionFecha { get; set; }
        public Nullable<int> UsuarioCreadorId { get; set; }
        public Nullable<int> CheckListId { get; set; }
    
        public virtual dtCheckList1 dtCheckList1 { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
    }
}
