//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtExamenPsicometrico
    {
        public int PsicometricoId { get; set; }
        public int TramiteId { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public string Eres { get; set; }
        public string Habilidades { get; set; }
        public Nullable<int> Artisticos { get; set; }
        public Nullable<int> Sociales { get; set; }
        public Nullable<int> Cientificos { get; set; }
        public Nullable<int> Atleticos { get; set; }
        public Nullable<int> Matematicas { get; set; }
        public Nullable<int> Musica { get; set; }
        public Nullable<int> Filosofia { get; set; }
        public Nullable<int> Letras { get; set; }
        public Nullable<int> Alegres { get; set; }
        public Nullable<int> Organizadores { get; set; }
        public Nullable<int> Sonadores { get; set; }
        public Nullable<int> Practicos { get; set; }
        public Nullable<int> Formulas { get; set; }
        public Nullable<int> Procedimientos { get; set; }
        public Nullable<int> Imagenes { get; set; }
        public Nullable<int> Sentimientos { get; set; }
        public Nullable<int> Imaginativos { get; set; }
        public Nullable<int> Inspiradores { get; set; }
        public Nullable<int> Cuestionadores { get; set; }
        public Nullable<int> Disciplinados { get; set; }
        public Nullable<int> Creativo { get; set; }
        public Nullable<int> Emocional { get; set; }
        public Nullable<int> Tecnico { get; set; }
        public Nullable<int> Comunicativo { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaInicioVigencia { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
    }
}
