//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtFactura
    {
        public int FacturaId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string UUID { get; set; }
        public string Serie { get; set; }
        public string Folio { get; set; }
        public string Version { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ImporteLetra { get; set; }
        public Nullable<decimal> OtroImpuesto { get; set; }
        public Nullable<decimal> IVARetenido { get; set; }
        public Nullable<decimal> ISRRetenido { get; set; }
        public string NumCuentaPredial { get; set; }
        public string Tipo { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int UsuarioModificoId { get; set; }
        public Nullable<int> ProyectoId { get; set; }
        public Nullable<int> TareaId { get; set; }
        public System.DateTime FechaCrecion { get; set; }
        public System.DateTime FechaModificion { get; set; }
        public Nullable<int> FacturaCategoriaId { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaGasto { get; set; }
        public Nullable<int> AgrupadorId { get; set; }
    
        public virtual dtAgrupador dtAgrupador { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtFacturaCategoria dtFacturaCategoria { get; set; }
        public virtual dtProyecto dtProyecto { get; set; }
        public virtual dtTarea dtTarea { get; set; }
    }
}
