//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtFormaEjecutiva
    {
        public int FormaEjecutivaId { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Modulo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaEstatus { get; set; }
        public Nullable<int> UsuarioEstatus { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<int> ConcesionId { get; set; }
        public Nullable<bool> EnviadoaC4 { get; set; }
    
        public virtual dtConcesione dtConcesione { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEstatusLicencia dtEstatusLicencia { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
    }
}
