//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtGaleriaDetalle
    {
        public int DetalleId { get; set; }
        public Nullable<int> GaleriaId { get; set; }
        public string ImgPath { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual dtGaleria dtGaleria { get; set; }
    }
}
