//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtImporte
    {
        public int ImporteId { get; set; }
        public int VigenciaId { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> Concepto { get; set; }
        public Nullable<int> Descuento { get; set; }
        public bool Activo { get; set; }
        public int UsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual dtVigencia dtVigencia { get; set; }
    }
}
