//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtJerarquia
    {
        public int JerarquiaId { get; set; }
        public string DI_EEVV { get; set; }
        public string DO_EEVV { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> CanalId { get; set; }
        public Nullable<int> SubCanalId { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> TerritorioId { get; set; }
        public string Plaza { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> SubdirectorId { get; set; }
        public Nullable<int> JefeId { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
    
        public virtual dtCanal dtCanal { get; set; }
        public virtual dtRegion dtRegion { get; set; }
        public virtual dtSubCanal dtSubCanal { get; set; }
        public virtual dtTerritorio dtTerritorio { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
    }
}
