//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMarker
    {
        public int MarkersId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<System.DateTime> FechaMarker { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> CampaniaId { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> ContactoId { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
