//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMeta
    {
        public int MetaId { get; set; }
        public int EmpresaId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public Nullable<int> UsuarioModificoId { get; set; }
        public Nullable<int> UsuarioMetaId { get; set; }
        public Nullable<int> GrupoMetaId { get; set; }
        public string TipoClave { get; set; }
        public Nullable<decimal> MontoVenta { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> EtapaId { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> CampanaId { get; set; }
    
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtEtapa dtEtapa { get; set; }
        public virtual dtGrupo dtGrupo { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
    }
}
