//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtModuloAsignacion
    {
        public int EmpresaId { get; set; }
        public string ModuloClave { get; set; }
        public int VinculoId { get; set; }
        public Nullable<int> UsuarioAsignoId { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string Tipo { get; set; }
        public string PermisoClave { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtGrupo dtGrupo { get; set; }
        public virtual dtModulo dtModulo { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
