//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtModuloRespuestaOpcion
    {
        public string ModuloClave { get; set; }
        public int VinculoId { get; set; }
        public int CampoId { get; set; }
        public int RespuestaId { get; set; }
    
        public virtual dtCampoRespuesta dtCampoRespuesta { get; set; }
        public virtual dtCampos dtCampos { get; set; }
        public virtual dtModulo dtModulo { get; set; }
    }
}
