//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtModuloRespuesta
    {
        public int RespuestaValorId { get; set; }
        public string ModuloClave { get; set; }
        public int CampoId { get; set; }
        public int VinculoId { get; set; }
        public string Valor { get; set; }
        public string ValorBruto { get; set; }
        public string Tipo { get; set; }
        public string XmlCampo { get; set; }
        public Nullable<decimal> ValorNumerico { get; set; }
        public Nullable<int> CampoGrupoId { get; set; }
        public Nullable<decimal> ValorMaximoNumerico { get; set; }
        public string ClaveSync { get; set; }
    
        public virtual dtCampoGrupo dtCampoGrupo { get; set; }
        public virtual dtCampos dtCampos { get; set; }
        public virtual dtModulo dtModulo { get; set; }
    }
}
