//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMoviqSva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtMoviqSva()
        {
            this.dtCotizacionDetalleSvas = new HashSet<dtCotizacionDetalleSva>();
        }
    
        public int SvaId { get; set; }
        public int ServicioId { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioMensual { get; set; }
        public string Modalidad { get; set; }
        public Nullable<int> Plazo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int UsuarioModificadorId { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCotizacionDetalleSva> dtCotizacionDetalleSvas { get; set; }
        public virtual dtMoviqServicio dtMoviqServicio { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
