//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMovimiento
    {
        public int MovimientoId { get; set; }
        public string MesaControlId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string Expediente { get; set; }
        public int Ramo { get; set; }
        public int Aseguradora { get; set; }
        public int Producto { get; set; }
        public int TipoMovId { get; set; }
        public int AseguradoId { get; set; }
        public Nullable<int> MotivoEndoso { get; set; }
        public string ObservaEndoso { get; set; }
        public System.DateTime FechaSol { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaReasignacion { get; set; }
        public int AreaId { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> TipoDomEnv { get; set; }
        public string Poliza { get; set; }
        public Nullable<int> Concluido { get; set; }
        public int UsuarioCreadorId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string RFC { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Calle { get; set; }
        public string NumInt { get; set; }
        public string NumExt { get; set; }
        public string Colonia { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public string CP { get; set; }
        public string Municipio { get; set; }
        public string Semaforo { get; set; }
        public Nullable<System.DateTime> FechaPrimeraReasignacion { get; set; }
        public Nullable<int> NumPromotor { get; set; }
        public string DescripcionCT { get; set; }
        public Nullable<short> EstadoIdCT { get; set; }
    }
}
