//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMoviqSocrinTipoCliente
    {
        public int TipoClienteScoringId { get; set; }
        public Nullable<int> ScoringId { get; set; }
        public Nullable<int> TipoClienteId { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
    
        public virtual dtMoviqScoring dtMoviqScoring { get; set; }
        public virtual dtMoviqTipoCliente dtMoviqTipoCliente { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
