//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMoviqScoring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtMoviqScoring()
        {
            this.dtMoviqSocrinTipoClientes = new HashSet<dtMoviqSocrinTipoCliente>();
        }
    
        public int ScoringId { get; set; }
        public Nullable<decimal> FullPriceInicial { get; set; }
        public Nullable<decimal> FullPriceFinal { get; set; }
        public Nullable<int> FormaPagoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
    
        public virtual dtMoviqFormaPago dtMoviqFormaPago { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqSocrinTipoCliente> dtMoviqSocrinTipoClientes { get; set; }
    }
}
