//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMovimientosHistorial
    {
        public int MovHistoriaId { get; set; }
        public int MovimientoId { get; set; }
        public string MesaControlId { get; set; }
        public string Expediente { get; set; }
        public Nullable<int> Ramo { get; set; }
        public Nullable<int> Aseguradora { get; set; }
        public Nullable<int> Producto { get; set; }
        public int TipoMovId { get; set; }
        public int AseguradoId { get; set; }
        public Nullable<int> MotivoEndoso { get; set; }
        public string ObservaEndoso { get; set; }
        public System.DateTime FechaSol { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public int EstatusId { get; set; }
        public System.DateTime FechaReasignacion { get; set; }
        public int AreaId { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> TipoDomEnv { get; set; }
        public string Poliza { get; set; }
        public Nullable<int> Concluido { get; set; }
        public int UsuarioCreadorId { get; set; }
    }
}
