//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMuroDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtMuroDetalle()
        {
            this.dtArchivoes = new HashSet<dtArchivo>();
            this.dtModuloDetalleComentarios = new HashSet<dtModuloDetalleComentario>();
            this.dtMuroDetalleUsuarios = new HashSet<dtMuroDetalleUsuario>();
            this.dtMuroDetalleVisitadoes = new HashSet<dtMuroDetalleVisitado>();
            this.dtMuroLikes = new HashSet<dtMuroLike>();
        }
    
        public int MuroDetalleId { get; set; }
        public Nullable<int> MuroId { get; set; }
        public string Mensaje { get; set; }
        public int UsuarioId { get; set; }
        public string Url { get; set; }
        public string ImageSrc { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public bool Privada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivo> dtArchivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloDetalleComentario> dtModuloDetalleComentarios { get; set; }
        public virtual dtMuro dtMuro { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroDetalleUsuario> dtMuroDetalleUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroDetalleVisitado> dtMuroDetalleVisitadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroLike> dtMuroLikes { get; set; }
    }
}
