//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtMunicipio
    {
        public short EstadoId { get; set; }
        public short MunicipioId { get; set; }
        public string MunicipioNombre { get; set; }
    
        public virtual dtEstado dtEstado { get; set; }
        public virtual dtEstado dtEstado1 { get; set; }
    }
}
