//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtNoticia
    {
        public int NoticiaId { get; set; }
        public string Titulo { get; set; }
        public int UsuarioCreadoId { get; set; }
        public int UsuarioModificoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string ContenidoNoticia { get; set; }
        public string ImagenPrincipal { get; set; }
        public string Resumen { get; set; }
        public bool Activo { get; set; }
        public string Segmento { get; set; }
    
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
