//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtNota
    {
        public int NotaId { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string NotaDesc { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public int CreadorId { get; set; }
        public int ModificadorId { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<int> OportunidadId { get; set; }
        public Nullable<int> ProductoServicioId { get; set; }
        public string OrgienCodigo { get; set; }
        public Nullable<int> ReunionId { get; set; }
    
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtProductoServicio dtProductoServicio { get; set; }
        public virtual dtReunion dtReunion { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
