//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtObjetivoHistorial
    {
        public int ObjetivoTrackId { get; set; }
        public int ObjetivoId { get; set; }
        public Nullable<int> PorcentajeAvance { get; set; }
        public int UsuarioId { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual dtObjetivo dtObjetivo { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
