//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtOportunidadHistorial
    {
        public int HistorialId { get; set; }
        public int OportunidadId { get; set; }
        public Nullable<decimal> Probabilidad { get; set; }
        public Nullable<int> EtapaId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCambio { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> SourceId { get; set; }
        public bool EtapaAvance { get; set; }
    
        public virtual dtEtapa dtEtapa { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
