//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtOportunidadContacto
    {
        public int EmpresaId { get; set; }
        public int OportunidadId { get; set; }
        public int ContactId { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<int> UsuarioAsignoId { get; set; }
    
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
