//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtOportunidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtOportunidad()
        {
            this.dtArchivoes = new HashSet<dtArchivo>();
            this.dtCrmAsignacions = new HashSet<dtCrmAsignacion>();
            this.dtNotas = new HashSet<dtNota>();
            this.dtOportunidadContactoes = new HashSet<dtOportunidadContacto>();
            this.dtOportunidadHistorials = new HashSet<dtOportunidadHistorial>();
            this.dtOportunidadProductoes = new HashSet<dtOportunidadProducto>();
            this.dtProyectoes = new HashSet<dtProyecto>();
            this.dtTareas = new HashSet<dtTarea>();
        }
    
        public int OportunidadId { get; set; }
        public Nullable<int> EtapaId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Probabilidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioCreadorId { get; set; }
        public int UsuarioModificoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<System.DateTime> FechaStatus { get; set; }
        public int UsuarioEstatusId { get; set; }
        public string TipoAcceso { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> CampanaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivo> dtArchivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCrmAsignacion> dtCrmAsignacions { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtEtapa dtEtapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNota> dtNotas { get; set; }
        public virtual dtSource dtSource { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
        public virtual dtUsuario dtUsuario3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidadContacto> dtOportunidadContactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidadHistorial> dtOportunidadHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidadProducto> dtOportunidadProductoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProyecto> dtProyectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
    }
}
