//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtPagoHistorial
    {
        public int PagoId { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string PaqueteCodigo { get; set; }
        public string TipoSubscripcionCode { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string Estatus { get; set; }
        public string PayPalRaw { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtPaquete dtPaquete { get; set; }
    }
}
