//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtPlanProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtPlanProducto()
        {
            this.dtCotizacionDetalles = new HashSet<dtCotizacionDetalle>();
        }
    
        public int PlanProductoId { get; set; }
        public string CodigoPlan { get; set; }
        public Nullable<int> PlazoNumero { get; set; }
        public string CodigoScl { get; set; }
        public string CodigoSAP { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tecnologia { get; set; }
        public Nullable<decimal> CargoInicial { get; set; }
        public Nullable<decimal> PagoMensual { get; set; }
        public Nullable<System.DateTime> Actualizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Bandera { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> PrecioReferencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCotizacionDetalle> dtCotizacionDetalles { get; set; }
    }
}
