//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtProductoApartado
    {
        public int ProductoApartadoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> AlmacenId { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> ApartadoId { get; set; }
    
        public virtual dtApartado dtApartado { get; set; }
    }
}
