//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtRegistroEquipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtRegistroEquipo()
        {
            this.dtTokenLogins = new HashSet<dtTokenLogin>();
        }
    
        public int RegistroEquipoId { get; set; }
        public string Equipo { get; set; }
        public Nullable<int> ModuloId { get; set; }
        public string NombreUsuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual dtDestino dtDestino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTokenLogin> dtTokenLogins { get; set; }
    }
}
