//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtReunionIntegrante
    {
        public int ReunionIntegranteId { get; set; }
        public int ReunionId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public string IntegranteTipo { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtReunion dtReunion { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
