//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtReunionAcuerdo
    {
        public int ReunionAcuerdoId { get; set; }
        public Nullable<int> ReunioinId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Cumplida { get; set; }
    
        public virtual dtReunion dtReunion { get; set; }
    }
}
