//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTareaRecurso
    {
        public int RelacionId { get; set; }
        public int EmpresaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public int TareaId { get; set; }
        public string RoleCode { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
        public Nullable<int> usuarioAsignoId { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public string Tipo { get; set; }
    
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtGrupo dtGrupo { get; set; }
        public virtual dtTarea dtTarea { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
    }
}
