//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtTarea()
        {
            this.dtActividads = new HashSet<dtActividad>();
            this.dtFacturas = new HashSet<dtFactura>();
            this.dtTareaPasoes = new HashSet<dtTareaPaso>();
            this.dtTareaRecursos = new HashSet<dtTareaRecurso>();
            this.dtTarea1 = new HashSet<dtTarea>();
            this.dtTareas = new HashSet<dtTarea>();
        }
    
        public int TareaId { get; set; }
        public int EmpresaId { get; set; }
        public string TareaDescripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> ProyectoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaStatus { get; set; }
        public int CreadorId { get; set; }
        public int ModificoId { get; set; }
        public Nullable<int> UsuarioStatusId { get; set; }
        public string TipoCode { get; set; }
        public string OrgienCodigo { get; set; }
        public Nullable<int> ContactoId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public Nullable<int> OportunidadId { get; set; }
        public Nullable<int> ProductoServicioId { get; set; }
        public Nullable<int> ReunionId { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Resultado { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> MotivoId { get; set; }
        public Nullable<bool> LLamadaSaliente { get; set; }
        public string NumeroMarcado { get; set; }
        public Nullable<int> ObjetivoId { get; set; }
        public Nullable<int> RecurrenteId { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> CampanaId { get; set; }
        public Nullable<int> TareaParentId { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtActividad> dtActividads { get; set; }
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtContacto dtContacto { get; set; }
        public virtual dtCuenta dtCuenta { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFactura> dtFacturas { get; set; }
        public virtual dtLlamadaMotivo dtLlamadaMotivo { get; set; }
        public virtual dtModulo dtModulo { get; set; }
        public virtual dtObjetivo dtObjetivo { get; set; }
        public virtual dtOportunidad dtOportunidad { get; set; }
        public virtual dtProductoServicio dtProductoServicio { get; set; }
        public virtual dtProyecto dtProyecto { get; set; }
        public virtual dtReunion dtReunion { get; set; }
        public virtual dtStatu dtStatu { get; set; }
        public virtual dtTareaFrecuencia dtTareaFrecuencia { get; set; }
        public virtual dtTareaTipo dtTareaTipo { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTareaPaso> dtTareaPasoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTareaRecurso> dtTareaRecursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTarea1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
    }
}
