//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTagModulo
    {
        public int TagId { get; set; }
        public string ModuloClave { get; set; }
        public int VinculoId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual dtModulo dtModulo { get; set; }
        public virtual dtTag dtTag { get; set; }
    }
}
