//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTipoMovPorProducto
    {
        public int RamoId { get; set; }
        public int AseguradoraId { get; set; }
        public int ProductoId { get; set; }
        public int TipoMovId { get; set; }
        public Nullable<int> Estandar { get; set; }
        public Nullable<int> UsuarioResponsableId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
