//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTicket
    {
        public int TicketId { get; set; }
        public int EmpresaId { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public System.DateTime FechaTicket { get; set; }
        public System.DateTime FechaEstatus { get; set; }
        public Nullable<int> UsuarioCreadorId { get; set; }
        public Nullable<int> UsuarioModificoId { get; set; }
        public Nullable<int> UsuarioTicketId { get; set; }
        public string EstatusCodigo { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> CampaniaId { get; set; }
        public string ModuloClave { get; set; }
        public Nullable<int> VinculoId { get; set; }
    
        public virtual dtCampania dtCampania { get; set; }
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtUsuario dtUsuario1 { get; set; }
        public virtual dtUsuario dtUsuario2 { get; set; }
    }
}
