//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTipoMovimientoSol
    {
        public int TipoMovId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> RamoId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioCreadorId { get; set; }
        public Nullable<int> AseguradoraId { get; set; }
        public Nullable<int> Estandar { get; set; }
    }
}
