//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTokenLogin
    {
        public int TokenId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> FechaFinVigencia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Equipo { get; set; }
        public Nullable<int> RegistroEquipoId { get; set; }
        public Nullable<int> ModuloId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual dtDestino dtDestino { get; set; }
        public virtual dtRegistroEquipo dtRegistroEquipo { get; set; }
        public virtual dtUsuario dtUsuario { get; set; }
    }
}
