//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtTramite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtTramite()
        {
            this.dtArchivoTramites = new HashSet<dtArchivoTramite>();
            this.dtCapacitacions = new HashSet<dtCapacitacion>();
            this.dtContestadoFormularios = new HashSet<dtContestadoFormulario>();
            this.dtExamenMedicoes = new HashSet<dtExamenMedico>();
            this.dtExamenToxicoes = new HashSet<dtExamenToxico>();
            this.dtLicencias = new HashSet<dtLicencia>();
        }
        public string MotivoRe { get; set; }
        public string FVialis { get; set; }
        public string EstatusH { get; set; }
        public int TramiteId { get; set; }
        public string FolioAsignadoPlastico { get; set; }
        public int TipoLicenciaId { get; set; }
        public string TipoLicencia { get; set; }
        public string TipoTramite { get; set; }
        public int AniosVigencia { get; set; }
        public decimal Importe { get; set; }
        public string FolioPago { get; set; }
        public string OrderCobro { get; set; }
        public Nullable<System.DateTime> FechaExpedicion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaAntiguedad { get; set; }
        public string TipoIdentificacion { get; set; }
        public string ComporbanteDomicilio { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaEstatus { get; set; }
        public string Curp { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string FolioActaNacimiento { get; set; }
        public string Calle { get; set; }
        public string NoExterior { get; set; }
        public string NoInterior { get; set; }
        public Nullable<short> Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public Nullable<short> EstadoID { get; set; }
        public Nullable<short> MunicipioId { get; set; }
        public Nullable<short> LocalidadId { get; set; }
        public string Nacionalidad { get; set; }
        public string LugarOrigen { get; set; }
        public string Ocupacion { get; set; }
        public string EdoCivil { get; set; }
        public string Sexo { get; set; }
        public string TipoSangre { get; set; }
        public Nullable<bool> DonacionOrganos { get; set; }
        public string Complexion { get; set; }
        public Nullable<decimal> Estatura { get; set; }
        public string Piel { get; set; }
        public string Cabello { get; set; }
        public string Alergias { get; set; }
        public string Cara { get; set; }
        public string Ojos { get; set; }
        public string Nariz { get; set; }
        public string Boca { get; set; }
        public string SeñasParticulares { get; set; }
        public int UsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> UsuarioPreRegistro { get; set; }
        public Nullable<int> UsuarioRegistro { get; set; }
        public Nullable<int> UsuarioBiometrico { get; set; }
        public Nullable<int> IntentosExamen { get; set; }
        public string Correo { get; set; }
        public Nullable<int> ConsecutivoGeneral { get; set; }
        public Nullable<int> ConsecutivoDestino { get; set; }
        public string NumeroLicencia { get; set; }
        public string CodigoPago { get; set; }
        public Nullable<System.DateTime> FechaVenPago { get; set; }
        public string FolioControlEstado { get; set; }
        public string FolioSeguimiento { get; set; }
        public string LineaCapturaPago { get; set; }
        public string MensajePago { get; set; }
        public string UrlFormatoPago { get; set; }
        public string ReferenciaOxxo { get; set; }
        public Nullable<int> DestinoId { get; set; }
        public Nullable<int> Concepto { get; set; }
        public string RFC { get; set; }
        public byte[] FotoLic { get; set; }
        public byte[] FingerLeft_10 { get; set; }
        public byte[] FingerLeft_9 { get; set; }
        public byte[] FingerLeft_8 { get; set; }
        public byte[] FingerLeft_7 { get; set; }
        public byte[] thumbs_6 { get; set; }
        public byte[] FingerRight_5 { get; set; }
        public byte[] FingerRight_4 { get; set; }
        public byte[] FingerRight_3 { get; set; }
        public byte[] FingerRight_2 { get; set; }
        public byte[] thumbs_1 { get; set; }
        public string FirmaLic { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Localidad { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaUltimoExamen { get; set; }
        public string EstadoN { get; set; }
        public string MunicipioN { get; set; }
        public string ColoniaN { get; set; }
        public Nullable<bool> ExamenAprobado { get; set; }
        public string LetraConsecutiva { get; set; }
        public string TipoTel { get; set; }
        public string Lada { get; set; }
        public string RefAd { get; set; }
        public Nullable<bool> ImprimeDir { get; set; }
        public string NombreTutor { get; set; }
        public string APaternoTutor { get; set; }
        public string AMaternoTutor { get; set; }
        public Nullable<bool> SinRestricciones { get; set; }
        public Nullable<bool> Lentes { get; set; }
        public Nullable<bool> Protesis { get; set; }
        public Nullable<bool> Auditivo { get; set; }
        public Nullable<bool> LentesContacto { get; set; }
        public Nullable<bool> VehiculoAdaptado { get; set; }
        public Nullable<bool> VehiculoAutomatico { get; set; }
        public string Ben1Nombre { get; set; }
        public string Ben1APaterno { get; set; }
        public string Ben1AMaterno { get; set; }
        public string Ben1Parentezco { get; set; }
        public Nullable<decimal> Ben1Porcentaje { get; set; }
        public string Ben2Nombre { get; set; }
        public string Ben2APaterno { get; set; }
        public string Ben2AMaterno { get; set; }
        public string Ben2Parentezco { get; set; }
        public Nullable<decimal> Ben2Porcentaje { get; set; }
        public string Ben3Nombre { get; set; }
        public string Ben3APaterno { get; set; }
        public string Ben3AMaterno { get; set; }
        public string Ben3Parentezco { get; set; }
        public Nullable<decimal> Ben3Porcentaje { get; set; }
        public string TipoVig { get; set; }
        public string FolioExpediente { get; set; }
        public Nullable<bool> Corazon { get; set; }
        public Nullable<bool> Higado { get; set; }
        public Nullable<bool> Rinon { get; set; }
        public Nullable<bool> Corneas { get; set; }
        public string LicenciaAnterior { get; set; }
        public Nullable<int> VigenciaId { get; set; }
        public string TipoServicio { get; set; }
        public Nullable<int> CiudadanoId { get; set; }
        public Nullable<bool> Van { get; set; }
        public Nullable<bool> Bus { get; set; }
        public Nullable<bool> Taxi { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<bool> ToxicologicoVigente { get; set; }
        public Nullable<bool> NumeroLicenciaCorrecto { get; set; }
        public string PeticionPago { get; set; }
        public string RespuestaPago { get; set; }
        public string ReciboPagoGenerado { get; set; }
        public string Ben1Otro { get; set; }
        public string Ben2Otro { get; set; }
        public string Ben3Otro { get; set; }
        public string FechaCita { get; set; }
        public string HoraCita { get; set; }
        public string ModuloCita { get; set; }
        public string NoId { get; set; }
        public string NoComprobante { get; set; }
        public string TestigoUno { get; set; }
        public string TestigoDos { get; set; }
        public string DescRobo { get; set; }
        public string DescExt { get; set; }
        public string TiempoExt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivoTramite> dtArchivoTramites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCapacitacion> dtCapacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContestadoFormulario> dtContestadoFormularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtExamenMedico> dtExamenMedicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtExamenToxico> dtExamenToxicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias { get; set; }
    }
}
