//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtUsuarioZona
    {
        public int UsuarioId { get; set; }
        public int ZonaId { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual dtUsuario dtUsuario { get; set; }
        public virtual dtZona dtZona { get; set; }
    }
}
