//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dtUsuario()
        {
            this.dtActividads = new HashSet<dtActividad>();
            this.dtAprobacionDatosPDVs = new HashSet<dtAprobacionDatosPDV>();
            this.dtAprobacionDatosPDVs1 = new HashSet<dtAprobacionDatosPDV>();
            this.dtAprobacionDatosPDVs2 = new HashSet<dtAprobacionDatosPDV>();
            this.dtAprobacionDatosPDVs3 = new HashSet<dtAprobacionDatosPDV>();
            this.dtAprobacionDatosPDVs4 = new HashSet<dtAprobacionDatosPDV>();
            this.dtArchivoes = new HashSet<dtArchivo>();
            this.dtArchivoTramites = new HashSet<dtArchivoTramite>();
            this.dtAreas = new HashSet<dtArea>();
            this.dtAsignacionUsuarioDestinoes = new HashSet<dtAsignacionUsuarioDestino>();
            this.dtBitacoraDocumentosConcesiones = new HashSet<dtBitacoraDocumentosConcesione>();
            this.dtBitacoraLicencias = new HashSet<dtBitacoraLicencia>();
            this.dtCampaniaContactoAsignadoes = new HashSet<dtCampaniaContactoAsignado>();
            this.dtCampaniaContactoContestadoes = new HashSet<dtCampaniaContactoContestado>();
            this.dtCampaniaUbicacionAsignadoes = new HashSet<dtCampaniaUbicacionAsignado>();
            this.dtCampaniaUbicacionContestadoes = new HashSet<dtCampaniaUbicacionContestado>();
            this.dtCapacitacions = new HashSet<dtCapacitacion>();
            this.dtCapacitacions1 = new HashSet<dtCapacitacion>();
            this.dtCapacitacions2 = new HashSet<dtCapacitacion>();
            this.dtCheckListPreguntas1 = new HashSet<dtCheckListPreguntas1>();
            this.dtConceptos = new HashSet<dtConcepto>();
            this.dtContactoes = new HashSet<dtContacto>();
            this.dtContactoes1 = new HashSet<dtContacto>();
            this.dtContactoes2 = new HashSet<dtContacto>();
            this.dtCoordenadas = new HashSet<dtCoordenada>();
            this.dtCorreoHistorials = new HashSet<dtCorreoHistorial>();
            this.dtCrmAsignacions = new HashSet<dtCrmAsignacion>();
            this.dtCrmAsignacions1 = new HashSet<dtCrmAsignacion>();
            this.dtCuotasPDVs = new HashSet<dtCuotasPDV>();
            this.dtCuotasPDVs1 = new HashSet<dtCuotasPDV>();
            this.dtDestinos = new HashSet<dtDestino>();
            this.dtDestinos1 = new HashSet<dtDestino>();
            this.dtDestinos2 = new HashSet<dtDestino>();
            this.dtDestinos3 = new HashSet<dtDestino>();
            this.dtDispositivoHistorials = new HashSet<dtDispositivoHistorial>();
            this.dtEmpresas = new HashSet<dtEmpresa>();
            this.dtEmpresaUsuarios = new HashSet<dtEmpresaUsuario>();
            this.dtFolioConocers = new HashSet<dtFolioConocer>();
            this.dtFormaEjecutivas = new HashSet<dtFormaEjecutiva>();
            this.dtFormaEjecutivas1 = new HashSet<dtFormaEjecutiva>();
            this.dtFormaEjecutivas2 = new HashSet<dtFormaEjecutiva>();
            this.dtGastoReportes = new HashSet<dtGastoReporte>();
            this.dtGrupoUsuarios = new HashSet<dtGrupoUsuario>();
            this.dtJerarquias = new HashSet<dtJerarquia>();
            this.dtJerarquias1 = new HashSet<dtJerarquia>();
            this.dtJerarquias2 = new HashSet<dtJerarquia>();
            this.dtLicencias = new HashSet<dtLicencia>();
            this.dtLicencias1 = new HashSet<dtLicencia>();
            this.dtLicencias2 = new HashSet<dtLicencia>();
            this.dtLogBloqueoCiudadanos = new HashSet<dtLogBloqueoCiudadano>();
            this.dtMarkers = new HashSet<dtMarker>();
            this.dtMetas = new HashSet<dtMeta>();
            this.dtMetas1 = new HashSet<dtMeta>();
            this.dtMetas2 = new HashSet<dtMeta>();
            this.dtModuloAsignacions = new HashSet<dtModuloAsignacion>();
            this.dtModuloAsignacions1 = new HashSet<dtModuloAsignacion>();
            this.dtModuloDetalleComentarios = new HashSet<dtModuloDetalleComentario>();
            this.dtMoviqScorings = new HashSet<dtMoviqScoring>();
            this.dtMoviqScorings1 = new HashSet<dtMoviqScoring>();
            this.dtMoviqServicios = new HashSet<dtMoviqServicio>();
            this.dtMoviqServicios1 = new HashSet<dtMoviqServicio>();
            this.dtMoviqSocrinTipoClientes = new HashSet<dtMoviqSocrinTipoCliente>();
            this.dtMoviqSocrinTipoClientes1 = new HashSet<dtMoviqSocrinTipoCliente>();
            this.dtMoviqSvas = new HashSet<dtMoviqSva>();
            this.dtMoviqSvas1 = new HashSet<dtMoviqSva>();
            this.dtMuroDetalles = new HashSet<dtMuroDetalle>();
            this.dtMuroDetalleUsuarios = new HashSet<dtMuroDetalleUsuario>();
            this.dtMuroDetalleVisitadoes = new HashSet<dtMuroDetalleVisitado>();
            this.dtMuroLikes = new HashSet<dtMuroLike>();
            this.dtNotas = new HashSet<dtNota>();
            this.dtNotas1 = new HashSet<dtNota>();
            this.dtNoticias = new HashSet<dtNoticia>();
            this.dtNoticias1 = new HashSet<dtNoticia>();
            this.dtObjetivoes = new HashSet<dtObjetivo>();
            this.dtObjetivoes1 = new HashSet<dtObjetivo>();
            this.dtObjetivoes2 = new HashSet<dtObjetivo>();
            this.dtObjetivoHistorials = new HashSet<dtObjetivoHistorial>();
            this.dtOportunidads = new HashSet<dtOportunidad>();
            this.dtOportunidads1 = new HashSet<dtOportunidad>();
            this.dtOportunidads2 = new HashSet<dtOportunidad>();
            this.dtOportunidads3 = new HashSet<dtOportunidad>();
            this.dtOportunidadContactoes = new HashSet<dtOportunidadContacto>();
            this.dtOportunidadHistorials = new HashSet<dtOportunidadHistorial>();
            this.dtProyectoes = new HashSet<dtProyecto>();
            this.dtProyectoes1 = new HashSet<dtProyecto>();
            this.dtProyectoRoles = new HashSet<dtProyectoRole>();
            this.dtRegistroTokens = new HashSet<dtRegistroToken>();
            this.dtReunions = new HashSet<dtReunion>();
            this.dtReunionIntegrantes = new HashSet<dtReunionIntegrante>();
            this.dtTareas = new HashSet<dtTarea>();
            this.dtTareas1 = new HashSet<dtTarea>();
            this.dtTareas2 = new HashSet<dtTarea>();
            this.dtTareaRecursos = new HashSet<dtTareaRecurso>();
            this.dtTareaRecursos1 = new HashSet<dtTareaRecurso>();
            this.dtTarjetasCirculacionConcesiones = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetasCirculacionConcesiones1 = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetasCirculacionConcesiones2 = new HashSet<dtTarjetasCirculacionConcesione>();
            this.dtTarjetonesConcesiones = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesConcesiones1 = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesConcesiones2 = new HashSet<dtTarjetonesConcesione>();
            this.dtTarjetonesMercantiles = new HashSet<dtTarjetonesMercantile>();
            this.dtTarjetonesMercantiles1 = new HashSet<dtTarjetonesMercantile>();
            this.dtTarjetonesMercantiles2 = new HashSet<dtTarjetonesMercantile>();
            this.dtTemplatePasos = new HashSet<dtTemplatePaso>();
            this.dtTickets = new HashSet<dtTicket>();
            this.dtTickets1 = new HashSet<dtTicket>();
            this.dtTickets2 = new HashSet<dtTicket>();
            this.dtTipoLicencias = new HashSet<dtTipoLicencia>();
            this.dtTipoLicencias1 = new HashSet<dtTipoLicencia>();
            this.dtTitulosConcesiones = new HashSet<dtTitulosConcesione>();
            this.dtTitulosConcesiones1 = new HashSet<dtTitulosConcesione>();
            this.dtTitulosConcesiones2 = new HashSet<dtTitulosConcesione>();
            this.dtTokenLogins = new HashSet<dtTokenLogin>();
            this.dtUsuarioZonas = new HashSet<dtUsuarioZona>();
            this.dtVigencias = new HashSet<dtVigencia>();
            this.dtVigencias1 = new HashSet<dtVigencia>();
            this.dtZonas = new HashSet<dtZona>();
        }
    
        public int UsuarioId { get; set; }
        public string Nombre { get; set; }
        public string APaterno { get; set; }
        public string AMaterno { get; set; }
        public string Email { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaVigenciaIni { get; set; }
        public Nullable<System.DateTime> FechaVigenciaFin { get; set; }
        public string EstatusId { get; set; }
        public string Fotografia { get; set; }
        public int EmpresaId { get; set; }
        public short RolId { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> PuestoId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> EstadoId { get; set; }
        public Nullable<bool> NotificacionesDiarias { get; set; }
        public Nullable<bool> NotificacionesTareas { get; set; }
        public Nullable<bool> NotificacionesReuniones { get; set; }
        public string Cluster { get; set; }
        public Nullable<int> Clave { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Modulo { get; set; }
        public string Curp { get; set; }
        public string Firma { get; set; }
        public byte[] Huella { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtActividad> dtActividads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAprobacionDatosPDV> dtAprobacionDatosPDVs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivo> dtArchivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArchivoTramite> dtArchivoTramites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtArea> dtAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtAsignacionUsuarioDestino> dtAsignacionUsuarioDestinoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraDocumentosConcesione> dtBitacoraDocumentosConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtBitacoraLicencia> dtBitacoraLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoAsignado> dtCampaniaContactoAsignadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaContactoContestado> dtCampaniaContactoContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionAsignado> dtCampaniaUbicacionAsignadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCampaniaUbicacionContestado> dtCampaniaUbicacionContestadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCapacitacion> dtCapacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCapacitacion> dtCapacitacions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCapacitacion> dtCapacitacions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCheckListPreguntas1> dtCheckListPreguntas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtConcepto> dtConceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContacto> dtContactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContacto> dtContactoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtContacto> dtContactoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCoordenada> dtCoordenadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCorreoHistorial> dtCorreoHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCrmAsignacion> dtCrmAsignacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCrmAsignacion> dtCrmAsignacions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCuotasPDV> dtCuotasPDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtCuotasPDV> dtCuotasPDVs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtDestino> dtDestinos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtDestino> dtDestinos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtDestino> dtDestinos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtDestino> dtDestinos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtDispositivoHistorial> dtDispositivoHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtEmpresa> dtEmpresas { get; set; }
        public virtual dtEmpresa dtEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtEmpresaUsuario> dtEmpresaUsuarios { get; set; }
        public virtual dtEstado dtEstado { get; set; }
        public virtual dtEstado dtEstado1 { get; set; }
        public virtual dtEstado dtEstado2 { get; set; }
        public virtual dtEstado dtEstado3 { get; set; }
        public virtual dtEstado dtEstado4 { get; set; }
        public virtual dtEstado dtEstado5 { get; set; }
        public virtual dtEstado dtEstado6 { get; set; }
        public virtual dtEstado dtEstado7 { get; set; }
        public virtual dtEstado dtEstado8 { get; set; }
        public virtual dtEstado dtEstado9 { get; set; }
        public virtual dtEstado dtEstado10 { get; set; }
        public virtual dtEstado dtEstado11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFolioConocer> dtFolioConocers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtFormaEjecutiva> dtFormaEjecutivas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtGastoReporte> dtGastoReportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtGrupoUsuario> dtGrupoUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtJerarquia> dtJerarquias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtJerarquia> dtJerarquias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtJerarquia> dtJerarquias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLicencia> dtLicencias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtLogBloqueoCiudadano> dtLogBloqueoCiudadanos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMarker> dtMarkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMeta> dtMetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMeta> dtMetas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMeta> dtMetas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloAsignacion> dtModuloAsignacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloAsignacion> dtModuloAsignacions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtModuloDetalleComentario> dtModuloDetalleComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqScoring> dtMoviqScorings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqScoring> dtMoviqScorings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqServicio> dtMoviqServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqServicio> dtMoviqServicios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqSocrinTipoCliente> dtMoviqSocrinTipoClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqSocrinTipoCliente> dtMoviqSocrinTipoClientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqSva> dtMoviqSvas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMoviqSva> dtMoviqSvas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroDetalle> dtMuroDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroDetalleUsuario> dtMuroDetalleUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroDetalleVisitado> dtMuroDetalleVisitadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtMuroLike> dtMuroLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNota> dtNotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNota> dtNotas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNoticia> dtNoticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtNoticia> dtNoticias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtObjetivo> dtObjetivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtObjetivo> dtObjetivoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtObjetivo> dtObjetivoes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtObjetivoHistorial> dtObjetivoHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidad> dtOportunidads3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidadContacto> dtOportunidadContactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtOportunidadHistorial> dtOportunidadHistorials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProyecto> dtProyectoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProyecto> dtProyectoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtProyectoRole> dtProyectoRoles { get; set; }
        public virtual dtPuesto dtPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtRegistroToken> dtRegistroTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtReunion> dtReunions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtReunionIntegrante> dtReunionIntegrantes { get; set; }
        public virtual dtRol dtRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarea> dtTareas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTareaRecurso> dtTareaRecursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTareaRecurso> dtTareaRecursos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetasCirculacionConcesione> dtTarjetasCirculacionConcesiones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesConcesione> dtTarjetonesConcesiones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTarjetonesMercantile> dtTarjetonesMercantiles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTemplatePaso> dtTemplatePasos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTicket> dtTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTicket> dtTickets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTicket> dtTickets2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTipoLicencia> dtTipoLicencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTipoLicencia> dtTipoLicencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTitulosConcesione> dtTitulosConcesiones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtTokenLogin> dtTokenLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtUsuarioZona> dtUsuarioZonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtVigencia> dtVigencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtVigencia> dtVigencias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtZona> dtZonas { get; set; }
    }
}
