//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class spfCatalogoGral
    {
        public int NumeroCatalogo { get; set; }
        public int ClaveCatalogo { get; set; }
        public string ClaveAlfanumerica { get; set; }
        public string Descripcion { get; set; }
        public short Estatus { get; set; }
    }
}
