//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class spfServiciosConcepto
    {
        public int NumeroServicio { get; set; }
        public int Cuenta { get; set; }
        public decimal Monto { get; set; }
        public bool Activo { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaSistema { get; set; }
    }
}
