//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroLicenciasChihuahua.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewContactoContestada
    {
        public int CampaniaId { get; set; }
        public int ContactoId { get; set; }
        public string TituloContacto { get; set; }
        public string MisAsignados { get; set; }
        public Nullable<int> ContestadoId { get; set; }
        public Nullable<System.DateTime> FechaContestado { get; set; }
        public Nullable<System.DateTime> FechaInicioContestado { get; set; }
        public Nullable<int> UsuarioContestadoId { get; set; }
        public string NombreCompletoContesto { get; set; }
        public string NombreUsuarioContesto { get; set; }
    }
}
